# This is a basic workflow to help you get started with Actions

name: Build and deploy to QA

on:
  push:
    branches:  
     - qa
    
jobs:

  deploy-qa:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: artifacts

    - name: deploy cloubhub v2
      env:
            target: ${{secrets.target}}
            replicas: ${{ secrets.replicas}}
            vcores: ${{ secrets.vcores}}
            environment: ${{secrets.environment_qa}} 
            name_mule_app: surexport-s-sap-qa    
            MULE_PASSWORD_SECRET: ${{secrets.mule_password_secret}}
            env: ${{secrets.ENV_QA}}
            encryptionKey: ${{secrets.ENCRYPTIONKEY_QA}}
            client_id : ${{secrets.CLIENT_ID_QA}}
            client_secret: ${{secrets.CLIENT_SECRET_QA}}

 
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy  \
         --settings  .maven/settings.xml \
         -Dmule.artifact=$artifactName -Dmule.artifact=$artifactName -Dcloudhub.target="$target" -Ddeployment.replicas"$replicas" -Ddeployment.vcores="$vcores" -Dcloudhub.environment="$environment" -Dcloudhub.application.name="$name_mule_app" -Denv="$env" -DencryptKey="$encryptionKey" -Dclient_id="$client_id" -Dclient_secret="$client_secret" -DskipDeploymentVerification="true"  \


